### ISSUE TITLE
Syntax incomplete on parameter blocks

### ISSUE THREAD

**Issue by shawnisingh** [AOMediaCodec/iac#104]
We have some concrete ideas brewing to fill in this information, hopefully to be proposed within a few days.

One quirk worth mentioning sooner than later, it may require creating new syntax rules (new data types that are used to declare both a self-documenting intuitive field name (e.g. master_mix_gain) and a function/class that has a bit more syntax (e.g., parse the parameter ID and a default gain value).

**Comment by tdaede** [comment]
Fixed by #119
