### ISSUE TITLE
Start code OBU should not have obu_redundant_copy set

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iac#123]

**Comment by sunghee-hwang** [comment]
Start cod OBU includes version and profile version field. So, it is valuable to use obu_redundant_copy to indicate whether it is redundant or not.
[As Is]
It shall always be set to 0 for the following obu_type values:
OBU_IA_Temporal_Delimiter
OBU_IA_Sync
OBU_IA_Audio_Frame
OBU_IA_Audio_Frame_ID0 to OBU_IA_Audio_Frame_ID21
OBU_IA_Start_Code

[To Be] 
It shall always be set to 0 for the following obu_type values:
OBU_IA_Temporal_Delimiter
OBU_IA_Sync
OBU_IA_Audio_Frame
OBU_IA_Audio_Frame_ID0 to OBU_IA_Audio_Frame_ID21
