### ISSUE TITLE
Parameter block OBUs obu_redundant_copy field should be specified

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iac#138]
e.g. it could be mandated to 1

**Comment by sunghee-hwang** [comment]
[As Is] Parameter Block OBUs may be provided redundantly, such that they contain the same data as a previously provided Parameter Block OBU for the same time region.

[Proposal] Parameter Block OBUs may be provided redundantly, such that they contain the same data as a previously provided Parameter Block OBU for the same time region. In this case, the "obu_redundant_copy" field in OBU header shall be set to 1.
