### ISSUE TITLE
Rules for the use of a new sample description entry

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/iac#23]
A common practice in ISOBMFF is to splice files, like 2 programs or one program and an ad. Splicing in ISOBMFF is not as simple as with MPEG-2 TS, unfortunately. The splicer has to merge the `moov` boxes from both files into 1 `moov`. In the case of a single-track, this means merging the `trak` boxes and in particular they `stsd` boxes. Each codec needs to specify the rules when sample description entries can be merged. This should be done in this case too.

**Comment by cconcolato** [comment]
Based on https://github.com/AOMediaCodec/iac/issues/21#issuecomment-1066294309, it seems that any change in any of the static metadata parameter would trigger the creation of a new sample entry. In other words, when splicing 2 tracks, unless they have exactly the same sample description entry (bit comparison), you have to create 2 sample entries. 

It is not necessarily a problem but if we wanted to be able to use only one sample entry, we could keep in the sample entry only the parameters that are needed to create the `codecs` value (see #22) and move all the others to sample groups (e.g. Ambisonics Demixing Sample Group). These sample groups would be mostly constant, except for tracks resulting from splicing of tracks, where you would have long ranges of constant sample grouping.

**Comment by sunghee-hwang** [comment]
Does it mean that the fields should be same if we support both a single track and multiple tracks?

**Comment by cconcolato** [comment]
In this issue, I'm only considering single track. Splicing of content with multiple tracks is more complicated.

**Comment by sunghee-hwang** [comment]
Let me check my understanding.
For example when we try to splice 2 single-track files, for example one for Channel Audio with 10s duration and the other one for Ambisonics with 10s duration.(i.e the spliced file with 20s duration would have Channel audio for the first 10s and Ambisonics for the other 10s.)
If static metadata locates in sample entry, we need two sample entries to splice it. But we move static metadata to samplegroup, then one sample entry can work for it while we need one sample group for the first file and the other sample group for the other file.
Am I correct?

**Comment by cconcolato** [comment]
Yes.

**Comment by sunghee-hwang** [comment]
My assumption on static metadata which was not changed at all in a track was in contents point of view and did not consider the splicing.
Now I understand that we need to consider the splicing. So, the static metadata can be changed sometimes (not frame by frame) in a track in file format point of view for the splicing case.
In this sense,  does this mean that stsd box has multiple sample entries for the splicing?

**Comment by cconcolato** [comment]
Yes. 

Theoretically, in ISOBMFF you could splice 2 single-file tracks that have very different sample entries, for example different codecs as long as the handler stays the same. In this case, the resulting file would have 1 track with 2 sample entries. However, such theoretical tracks would be problematic for players. In particular, the `codecs` parameter only describes the first sample entry. So if you'd change the codec mid-track (e.g. from Opus to AAC-LC), players might have a problem.

In practice, even with the same codec, splicing 2 single-file tracks could produce also 2 sample entries. For example, with AV1, if you splice 2 single-file tracks that have different profiles or levels, you can decide to keep one sample entry describing the maximum profile and level or have 2 entries, each with different profiles or levels.

In the IAC case, I think the spec should be such that :
a) processing sample entries when splicing is simple, typically as simple as "do a binary comparison of the 2 inputs sample entries and if they differ produce 2 output sample entries", 
b) splicing minimizes the number of sample entries in the output. This can be achieved by having specific rules such as "compare the fields, if the fields A, B, C differ between sample entries 1 and 2, create a sample entry with max (A1,A2), max(B1,B2) max(C1,C2)" or by moving as much information into sample groups.

**Comment by tdaede** [comment]
We will use a simple byte comparison of the sample description entries to determine if splicing is possible. The amount of data in the sample description should be minimized to maximize the opportunity for single sample description splicing.
