### ISSUE TITLE
Determine the degree of flexibility and list of channel layouts that should be supported

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iac#25]
Also compare to existing channel layout description formats.

**Comment by sunghee-hwang** [comment]
- Ogg Opus: Output channel count implies channel layout (e.g. 6 means 5.1ch,  8 means 7.1ch etc..)
- The optional field, ChannelLayout() of Audio sample entry defines azimuth and elevation angles for each channel and layout channel count comes from the sample entry.

**Comment by cconcolato** [comment]
We agree to with a fixed set of layouts in this version, and possibly have a future version number for different layouts.
