### ISSUE TITLE
Compare downmixing specification to existing options

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iac#26]
Compare fixed list of downmixing modes to those provided in the Opus-in-ISOBMFF spec and other ISOBMFF specifications.

**Comment by sunghee-hwang** [comment]
- RFC 7845 (Ogg Opus, CMF = 1) and RFC 8486 (Ambisonics, CMF = 2 or 3) provides stereo downmix matrices as spec text (not delivered)
- ISOBMFF defines 'dmix' box for downmix matricies as a child of Audio sample entry. Any M x N downmix matries and any coefficients can be delivered via this box, where, M = targetChannelCount and N = baseChannelCount. But N is not defined in this box but is defined in ChannelLayout box ('chnl'). As summarized, any M x N downmix matrices and any coefficients can be delivered by using two optional fields ChannelLayout('chnl') and DownMixInstructions('dmix') of Audio sample entry.

**Comment by cconcolato** [comment]
We agree to with a fixed set of downmix matrics in this version, and possibly have a future version number for different matrices.
