### ISSUE TITLE
Define how audio elements are "matched up" when multiple SampleGroups are used

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iac#69]
If some audio channels are not present in certain SampleGroups, etc, we still need a way to match up streams that should go to the same decoder. There doesn't seem to be enough information on how to do that in the existing specification.

**Comment by shawn-i-singh** [comment]
Hello Thomas, can you please remind us what was the example situation that raised this issue?  Thank you in advance!

**Comment by tdaede** [comment]
The streams in a file are continuous - other than at the beginning and end of a file, when there is preskip and end padding, the decoders are not re-initialized. If we have 3 substreams, 0, 1, and 2, and then remove (1) partway through the file (i.e. via IA_STATIC_META), we want the remaining two streams to continue to be fed to the (0) and (2) decoder.

This is a potential case where having substream IDs would make this easy. It's not the only way to solve this issue, though. We could also just have a fixed set of rules to how streams are mapped (e.g. you're only allowed to add or remove from the end). We could also require complete decoder re-initialization every time IA_STATIC_META changes, though this has implications for being gapless through the transition.

**Comment by sunghee-hwang** [comment]
Simply, we may need to restrict that every Substreams have the same duration.

**Comment by tdaede** [comment]
This will be solved with the Sync OBU changes when those land, hopefully.
