### ISSUE TITLE
Consider defining a Temporal Delimiter OBU

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/iac#98]
Temporal Delimiter OBUs help simple parsers (e.g. in packagers or in players) to identify boundaries of bitstream parts that have the same timing. The drawback is the overhead associated with it. However, their use could be made optional, which means that:
 - encoders should generate them when it is desired to simplify the tasks of packagers or of simple readers but may remove them for applications where the overhead is too costly
 - there would exists 2 classes of readers: those that can process a bitstream without delimiters (e.g. full decoder) and those that cannot (e.g. simple parsers)
 - when stored in container formats that already have mechanisms to represent time boundaries, temporal delimiters should be removed upon storage and reinserted upon extraction.

**Comment by felicialim** [comment]
The Temporal Delimiter OBU was added in [1].

[1] https://github.com/AOMediaCodec/iac/commit/ced91d8469b4f49ac8b11a669aa138a8ba42a0f9
